---
- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: remove redundant deps
  become: yes
  apt:
    autoremove: yes

- name: install deps
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

# - name: "Install Node.js 13"
#   shell:  |
#     curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
#     sudo apt-get install -y nodejs
#     sudo npm install -g n
#     sudo n 13.8.0
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes